### ISSUE TITLE
Readme link to live version doesn't work (404 Not Found)

### ISSUE THREAD

**Issue by Eilon** [mdn/todo-react#48]
The readme has a link to a live version of the app on this line: https://github.com/mdn/todo-react/blob/main/README.md?plain=1#L7

It links to https://mdn.github.io/todo-react-build/, which returns a 404:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/202643/208989887-f6439f06-dba8-4ab2-80e0-17408822240e.png">

**Comment by bsmth** [comment]
Thanks @Eilon, I'm aware of it, I'll be fixing it shortly 👍

**Comment by bsmth** [comment]
Should be fixed now: https://mdn.github.io/todo-react/

Closing as done. Thanks :)

**Comment by Eilon** [comment]
Wonderful, thanks for the quick action!
