### ISSUE TITLE
"ul has an implicit role of list" issue 

### ISSUE THREAD

**Issue by gwanghyeongim** [mdn/todo-react#7]
Hi. Thanks for the great react app example first of all. In [Beginnig our React todo list](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_todo_list_beginning#Project_starter_code), I replaced `function App(props)` as shown in the example, and I got the following error in my terminal on my Mac.

```
Compiled with warnings.                                                         
                                                                                
./src/App.js                                                                    
  Line 44:7:  The element ul has an implicit role of list. Defining this explici
tly is redundant and should be avoided  jsx-a11y/no-redundant-roles             
                                                                                
Search for the keywords to learn more about each warning.                       
To ignore, add // eslint-disable-next-line to the line before.
```

On line 44:7 is the next line and the rest follows:
```
      <ul
        role="list"
        className="todo-list stack-large stack-exception"
        aria-labelledby="list-heading"
      >
```

When I set ` // eslint-disable-next-line` at line 43, it threw another error messages, so I ended up reverting back. 

My question is will I have no problem following this tutorial, or should I set some setting to keep the error message from happening?

Below is my `package.json` file contents BTW:

```
{
  "name": "moz-todo-react",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

Thank you for your work.

**Comment by gwanghyeongim** [comment]
Now that I applied css rules in `src/index.css`, I realised that there is no problem following the tutorial so far. You may close the issue.

**Comment by chrisdavidmills** [comment]
@gwanghyeongim this is a bit of a funny situation; the key line in the article is

"If you want to learn more about why this is necessary, you can check out Scott O'Hara’s article, “Fixing Lists”." - have a read to see why we are doing this.
