### ISSUE TITLE
need to fix - onChange Event Issues

### ISSUE THREAD

**Issue by sayshark75** [mdn/todo-react#77]
### What information was incorrect, unhelpful, or incomplete?

How I am facing issues => When I click on Edit on any Todo and try to clear the entire field, I get the original text back again.

The issue occurred in =>  the Edit-Template.

### What did you expect to see?

The Input Field Must be completely Clear and User can type Entirely New Name of Todo.

### Do you have anything more you want to share?

That is enough to get a reference to the actual error point.

**Comment by RaviSolanki27** [comment]
attempt

**Comment by caugner** [comment]
I was able to reproduce the issue on https://mdn.github.io/todo-react/:

https://github.com/mdn/todo-react/assets/495429/9c23a443-2ac5-46fb-82b4-9da7f98a6152

**Comment by caugner** [comment]
The reason is `value={newName || props.name} ` here:

https://github.com/mdn/todo-react/blob/5dc43fa03f0bccacdb041d5a7882ce5395e04fea/src/components/Todo.js#L41-L48

As soon as `newName` is emptied, the `props.name` (aka the previous name) is shown.

Instead: `newName` should be initialized with `props.name` and `props.name` could be added as a `placeholder`.

**Comment by RaviSolanki27** [comment]
value={isEditing ? newName : props.name}
 
 Just do these changes and it will work

**Comment by sayshark75** [comment]
`<input
          id={props.id}
          className="todo-text"
          type="text"
          value={newName || props.name}
          onChange={handleChange}
          ref={editFieldRef}
        />`
- The Issue lies in the value, when newName becomes "", it uses props.name
- Instead, we can use onBlur Event on the input, and in onBlur event, we can check if the newName is Empty, then we will use the props.name.

**Comment by bsmth** [comment]
Thanks all, I'm closing this one as done now! Well done on the great approaches to improving the example! 👏🏻 

See 

- https://github.com/mdn/todo-react/pull/74
- https://github.com/mdn/todo-react/pull/92
