### ISSUE TITLE
Empty item is inserted in the UI

### ISSUE THREAD

**Issue by amos-kibet** [mdn/todo-react#8]
Hi, I have been following the to-do tutorial and I realized when you click the `Add` button without typing anything to the input field, it is rendered as a to-do item in the UI, only that it is empty(does not have a name).

**Comment by chrisdavidmills** [comment]
Hi @amos-kibet ! This is a good point — we've not added any kind of check into the code to disallow empty tasks from being added. I've added a note at the bottom of https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_interactivity_events_state#Updating_state to signal this, and ask readers to try to create their own solution.

It's pretty easy to do, therefore its a nice little exercise to let you try. Give me a ping if you run into troubles with it.

**Comment by amos-kibet** [comment]
Hi and thanks Chris Mill. I found a solution from one of the PRs in the
repo. I am really grateful for the resource.

**Comment by chrisdavidmills** [comment]
Right on! I am glad you are finding it helpful.
